
production:
  <<: *default
  database: furima_46712_production
  username: furima_46712
  password: <%= ENV["FURIMA_46712_DATABASE_PASSWORD"] %>

default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_46712_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-46712_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>